### ISSUE TITLE
Broken formatting for not implemented/deprecated

### ISSUE THREAD

**Issue by jsannemo** [Kattis/problem-package-format#25]
The formatting on kattis.com/problem-package-format/ is not working.

Also, the markup for not-implemented is broken for `input_validator_flags`, not showing what is not yet implemented. Looks like some </s> tags that should be <s>?

**Comment by jsannemo** [comment]
@niemela

**Comment by thorehusfeldt** [comment]
In fact, the markdown page at https://github.com/Kattis/problem-package-format/blob/master/spec/problem_package_format.md shows the entire definition of `input_format_validators` as <s>deprecated</s>, whereas the version as  https://www.kattis.com/problem-package-format/spec/problem_package_format#test-data-groups has

> arguments passed to the input validator for this test data group. If a string this is the name of the input validator that will be used for this test data group. If a map then this is the name as well as the flags that will be passed to the input validator.

**Comment by thorehusfeldt** [comment]
Alas, I can see that NIO 2021 used 
```yaml
input_validator_flags:
  name: input_validator
  flags: sub1
```
so to the extent that this is fixable at all, we’d need both
```yaml
input_validator_flags: 
  name: validator_name
  flags: --max_n 10 --connected
```
and
```yaml
input_validators: 
  name: validator_name
  flags: --max_n 10 --connected
```

So (unless I’m missing something) the specification should be: (The important part is the second sentence, starting with “If a string…”.)

* `input_validator_flags`. (**String** or **map**).  _Deprecated_. Arguments passed to the input validator for this test data group. If a string, it is passed to all input validators that will be used for this test data group. If a map then this is the name as well as the flags that will be passed to the input validator. 
* `input_validators`. (**String** or **map**.)  Arguments passed to the input validator for this test data group. If a string this is the name of the input validator that will be used for this test data group. If a map then this is the name as well as the flags that will be passed to the input validator. 

No tool implements either of these; BAPCtools implements the second under the name of the first; problemtools implements the `str` part of the first.
