### ISSUE TITLE
Can we make creation of scoring problems simpler

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#35]
Suggested by @jsannemo.

**Comment by niemela** [comment]
@jsannemo Please elaborate...

**Comment by RagnarGrootKoerkamp** [comment]
Given a nice skeleton, I could add this to `bt new_problem`

**Comment by thorehusfeldt** [comment]
In case anybody cares, here is an example of how a scoring problem works with the current `testdata.yaml` setup:
```yaml
testdata.yaml:
  on_reject: continue
  range: "0 100"
  grader_flags: first_error
data:
  sample:
    testdata.yaml:
      on_reject: continue
      range: 0 0
      accept_score: "0"
      grader_flags: first_error
  secret:
    testdata.yaml:
      on_reject: continue
      range: 0 100
      grader_flags: first_error accept_if_any_accepted
    data:
      group1:
        testdata.yaml:
          on_reject: break
          range: 0 30
          accept_score: "30"
          grader_flags: min      
      group2:
        testdata.yaml:
          on_reject: break
          range: 0 70
          accept_score: "70"
          grader_flags: min
```
Some time ago, I wrote this up in CUE for a scoring-problem-compatible `generator.yaml`, it looks like this:
```cue
    "testdata.yaml": {
        on_reject: "continue"
	range: data.secret."testdata.yaml".range
	grader_flags: "first_error"
    }
    data: sample: "testdata.yaml": {
        on_reject: "continue"
	range: "0 0"
	accept_score: "0"
	grader_flags: "first_error"
    }
    data: secret: "testdata.yaml": {
        on_reject: "continue"
	range: "0 \(list.Sum([for group in data.secret.data { strconv.Atoi(group."testdata.yaml".accept_score)}]))"
	grader_flags: "first_error accept_if_any_accepted"
    }
    data: secret: data: [string]: "testdata.yaml": {
        on_reject: "break"
	accept_score: =~ "[1-9][0-9]*"
	range: "0 \(accept_score)"
	grader_flags: "min"
    }
```
Note that the _only_ interesting values are _k_ many integer values of `accept_score`, one for every testgroup defined by `data:secret:data:<whatever>`, which are the testgroups what would end up in `<problem>/data/secret/<whatever>`. Everything else is just boilerplate that could be automatically generated. (In fact, CUE would be _able_ to automatically generate that, but that doesn’t help us and I’m not suggesting this.)

My idea was to introduce a tooling-specific toplevel key in `generators.yaml`, such as `scoring-testgroups: [...int]`, where the tool then automatically populates the `testdata.yaml` with the necessary boilerplate and _also_ restricts `testdata.yaml` keys in the rest of `generators.yaml` to only set `input_validator_flags`.

I similar toplevel key (`icpc`) could forbid the creation of testgroups below `data/secret/` and the creation of `testdata.yaml`. All of this can be very strictly specified in CUE (or precise English prose.)
