### ISSUE TITLE
`rights_owner`: Types, values, defaults, and inference

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#384]
### Summary of draft specification

The draft specification has, for  `problem.yaml`, the key `rights_owner` as `string`, with **Required** and **Defaults** as “see below”.

Below, under **License** we then learn

> `rights_owner` is the owner of the copyright of the problem. Values other than `unknown` or `public domain` require `rights_owner` to have a value. `rights_owner` defaults to `credits.authors`, if present, otherwise value of `source`.

The type of `credits.authors` is “Person or non-empty sequence of persons”. I think there is consensus that this means 

```cue
#Persons: #Person | [#Person, ...#Person] // singleton or nonempty list
credit: authors: #Persons
```
The key `source` has its own section in the specification: https://www.kattis.com/problem-package-format/spec/2023-07-draft.html#source . I think I have loyally summarised that section as:

```cue
// A problem source is typically a contest or course, such as "NWERC 2023" or { name: "NWERC 2023", url: "2023.nwerc.eu" }
#Source: string | {
	name!: string
	url?:  net.URL()
}
// The source(s) of this problem, such as "NWERC 2024"
source?: #Source | [#Source, ...#Source]
```

#### Type of `rights_owner`

The defaults of `rights_owner` (namely, `credits.authors` and `source`, in that order of preference) seem to imply that `rights_owner` must accommodate those types. For instance, in

```yaml
source:
    name: NWERC 2024
    url: 2024.nwerc.eu
```

I would expect `rights_owner` to have the value `{ name: NWERC 2024; url: 2024.nwerc.eu }`. If that is not intended, and `rights_owner` is indeed always _only_ `string`, the spec should make it clear: When `credits.source` is _not_ string but map, should then `credits.source.name` be chosen? Or is the above an error. The same question can be asked about

```yaml
credits.authors:
    - name: Alice
      email: alice@bar.baz
source:
    name: NWERC 2024
    url: 2024.nwerc.eu
```
Is `credits.authors[0].name` chosen? Or do the defaults “fall through” to `source.name`? Or is the above an _error_ because no rights are specified?

#### Default for credits: #Person

`credits` can be just `#Person`. In the simplest form,

```yaml
credits: Alice
source: NWERC 2024
```
who is the `rights_owner`? I think the specification says `NWERC 2024` (because `credits.authors` does not exist.) The alternative viewpoint is that when `credit: #Person` with value `foo` then this should be _the same_ as `credits.authors: foo`.

The two questions interplay because in

```yaml
credits:
    name: Alice
source: NWERC 2024
```
one may think “`credits.authors` not given hence NWERC owns the rights” or “`credits` given; clearly the intention is that the value of `credits` should implicitly populate the “implied” field `credits.authors`, so Alice has the rights” or  “Even though there is a `credits` field, the fact that it has type “map” rather than `string` means that is does _not_ count as a valid default (because `rights_owner` must be `string`), so we “fall through” to NWERC anyway. 

As usual, I have _no opinion_ on any of these interpretations; I just want us to specify.

#### Quiz

Here is my best attempt at a full set of questions that cover all the issues. In each case, who do you think owns the rights (alternatively, which snippets satisfy the requirements in terms of specifying this at all)? All these snippets assume mandatory fields defined and `license: cc0`.

```yaml
credits: Alice
source: AWERC # credits.author not given. Is the answer AWERC or Alice
---
credits:
  name: Bob
source: BWERC # credits not a string. Is the answer BWERC or Bob (or a map)
---
credits:
  name: Claire
  email: claire@a.com
source: CWERC  # credits not a string. Is the answer CWERC or Claire (or a map) or even "Claire <claire@a.com>"?
---
credits:
  - name: Doris
    email: doris@a.com
  - name: Diana
source: DWERC # credits is a list. DWERC or Doris or [Doris, Diana] (list of string? list of map, even)?
---
credits:
  authors: Erika
source: EWERC # rights owner is Erika
---
credits:
  authors:
    name: Fritz
    email: fritz@hans.com
source: FWERC # credits.authors no a string. So it’s FWERC?
---
credits:
  authors:
    name: Günther
    email: fritz@hans.com
source: 
    name: GWERC
    url: gwerc.de  # neither credits.author not source are strings.
```

#### Thore’s suggestion

My own suggestion is this:
```
rights_owner?: #Persons | #Source | [#Source, ...#Source]
```
With the following rules for defaults:

1. if `rights_owner` is concrete, then use `rights_owner`
2. if `credits` is `#Persons` then use `credits`
3. if `credits.authors` is concrete (and therefore has type `#Persons`) then use `credits.authors`
4. if `source` is concrete (and therefore has type `#Source | [#Source, ...#Source]`) then use `source`
5. ERROR

(This can be expressed in CUE but becomes very messy.)

**Comment by thorehusfeldt** [comment]
I had a pleasant phone conversation with @niemela . Here is the summary.

```cue
// Explicitly specify who owns the rights of this problem, such as "University of Waterloo" or "Alice McAuthorson <foo@bar.baz>" or "Alice Cooper and Bob Marley".
rights_owner: string
```

Do determine who owns the right of a the problem with `license` different from `"unkown"` and `"public domain"`, proceed as follows:

1. if `rights_owner` is concrete, then use the value of `rights_owner`
2. if `credits` is #`Persons` use the value of `credits`
3. if `credits` is a map and `credits.authors` is concrete (and therefore has type #`Persons`) then use the value of  `credits.authors`
4. if `source` is concrete (and therefore has type `#Source | [#Source, ...#Source]`) then use the value of `source`
5. ERROR

**Comment by niemela** [comment]
I has a discussion with @thorehusfeldt offline. This is my understanding of what we concluded.

The field `credits.author` is of "type" `#Persons`.
The field `source` is of "type" `#Sources`
The field `rights_owner` is of "type" `string`.

The rights owner (the "abstract concept", not the field in `problem.yaml`) is:
- What is specified in the `rights_owner` string, else if `rights_owner` is not given
- The person(s) specified as `credits.author`, else if `credits.author` is not given
- The legal entity (or person) owning the rights associated with `source`.

It's "technically" an error if the process above does not indicate some legal entity (e.g. if `rights_owner` is `"Unknown"` or `"That guy over there!"`, or if `rights_owner` and `credits.author` are missing and `source` is `"A course I was developing"`, and many other examples), but validating this is ***way*** out of scope.

**Comment by thorehusfeldt** [comment]
@niemela : you also need to specify what happens if `credits: #Persons`, such as
```yaml
credits: AliceMcAuthorson
---
credits:
  name: Alice
  email: a@b.c
---
credits: [Larry, Curly, Moe]
```
