### ISSUE TITLE
Extend credit list

### ISSUE THREAD

**Issue by Tagl** [Kattis/problem-package-format#67]
If a more granular set of credits should be supported, then what should be supported?

- Problem Authors (idea)
- Contributors (setup)
- Translators
- Testers
- (Dedications?)

**Comment by evouga** [comment]
Dedications seems dubious to me but maybe we do want a catch-all category like Special Thanks

**Comment by niemela** [comment]
Currently the author key is a simple string, so in the case of multiple authors:
```
author: Firstname Lastname and Firstname2 Lastname2
```

We should change this into a sequence of strings instead:
```
author:  ['Firstname Lastname', 'Firstname2 Lastname2']
```
or
```
author:
   - Firstname Lastname
   - Firstname2 Lastname2
```

If we are supporting more granular credits this would be a map from credits to sequences of strings, i.e. something like:
```
author:
   contributing:
      - Firstname Lastname
      - Firstname2 Lastname2
   testing: 
      - Firstname Lastname
      - Firstname2 Lastname2
```

But now `author` doesn't quite make sense at the key at the top level. What should we change this to? `credits`?

**Comment by jsannemo** [comment]
```yaml
credits:
    authors: Johan Sannemo <jsannemo@jsannemo.se>
    testers:
       - Fredrik N
       - Blah
    contributors:
       - Simon
```

**Comment by RagnarGrootKoerkamp** [comment]
`authors`, `contributers`, `testers` SGTM, but we should make it document what we mean by each. To me contributers sounds people who implemented it, which should rank 'higher' than testers

**Comment by niemela** [comment]
So far we seem to have:
- `authors` - Main author, and the default if nothing is specified
- `contributors` - Others that also did significant work on the problem
- `testers` - Self explanatory(?).
- `translators` - Translating to a natural language. Needs an "argument" somewhere. Should it be `translators-<lang>`?

We also mentioned at some point:
- solution provider - I feel that would fall under contributor or possibly tester?

Anything more we should support? Anything less?

**Comment by RagnarGrootKoerkamp** [comment]
i'd say 'solution provider' is the same as 'tester'; our testers read & solve the problem, suggest some small bugfixes to statements, and usually implement most of the set.

**Comment by Tagl** [comment]
To me there is definitely a difference between who suggests the concept of a task (author?) vs who implements it (contributor?, also called problem setter by some) although I think very often this is the same person or same people. Agree that tester covers people "solution provider".

**Comment by Tagl** [comment]
For  translators I see a two options:
```yaml
credits:
    translators-is:
        - Arnar Bjarni Arnarson <arnar.b.arnarson@gmail.com>
        - Samúel Arnar Hafsteinsson <samuelhafsteins@gmail.com>
    translators-se: Johan Sannemo <jsannemo@jsannemo.se>
```
or the one I like more:
```
```yaml
credits:
    translators:
        is:
            - Arnar Bjarni Arnarson <arnar.b.arnarson@gmail.com>
            - Samúel Arnar Hafsteinsson <samuelhafsteins@gmail.com>
        se: Johan Sannemo <jsannemo@jsannemo.se>
```

Do we need to clarify in which language the original statement was written for all of this to make sense? The metadata is not required so there isn't really an implication that the missing language is the original language.
