### ISSUE TITLE
Better identification of authors

### ISSUE THREAD

**Issue by niemela** [Kattis/problem-package-format#78]
(See also #67)

Currently we identify a problem author by their name as a string. We discussed allowing for a more unique identifier such as email or orcid.

This could look something like this:
```
author:
   - name: Firstname Lastname
   - email: firstname.lastname@email.com
   - orcid: https://orcid.org/0000-0001-5727-2427
```
`email` and `orcid` would be optional, and just a string would be interpreted as the `name`.

Thoughts?

**Comment by jsannemo** [comment]
So you would write something like:
```yaml
authors:
  - name: blah
    email: blah
  - name: blah
    email: blah
```
etc?

Seems kind of verbose. I won't use it, but it's metadata so I care much less about spec bloat.

I would slightly more often use the email format though, i.e.
```
authors:
  - Johan Sannemo <jsannemo@jsannemo.se>
  - Simon Lindholm <....>
 ```
would be ni
