### ISSUE TITLE
Semantics of `type: "scoring"` and `validation: {scoring: true}`

### ISSUE THREAD

**Issue by thorehusfeldt** [Kattis/problem-package-format#95]
Consider the following combination:

```yaml
name: Foo
type: scoring
validation:
  scoring: true
```

The problem (for me) is that the string `scoring` means two very different things here (the first is a claim about how grading is done and how the UI presents the result, the other is about the existence and behaviour of a program in `output_validators` that produces `score.txt`.)

I think this is very unclear to the uninitiated. In fact, the following combination looks very weird to me: 
```yaml
name: Foo
type: scoring
validation:
  scoring: false
```
I think this is a mess anyway. I welcome suggestions for cleaning this up, in particular if they _also_ could decouple the ICPC part from the full specification.
